---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list: 'recipe[berkshelf-test::default]'
    attributes:
      nginx:
        port: 80
